export const Tree: string;
export const tree: string;
export const directory: string;
export const closed: string;
export const opened: string;
export const file: string;
export const added: string;
export const deleted: string;
export const updated: string;
